### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Xaikii** [TeNNoX-Mods/Planetoids#10]
Hey, this is actually not a real issue, but rathermore a request. since u hadnt been online on any other platform, I think I can only contact you here. Would it be possible that this mod can be added to Curse's "NonCurseForge" List? Would like to use this mod in my modpack, but I am not allowed until you give permissions to Curse that User can use your Mod. Would be pretty nice :3

**Comment by tennox** [comment]
You are permitted to add this mod to lists or modpacks of your liking ;)

And I will keep this issue open, as I should probably add a LICENSE anyways for my mods - or even better, update them already ^^

**Comment by Xaikii** [comment]
Updating would be an idea ;)

I heard 1.10.2 should be the next great thing :D
